version: '3'
services:
  frontend:
    stdin_open: true
    container_name: frontend
    build: ./frontend
    ports:
      - 80:5173
    restart: always
  backend: 
    build: ./backend
    container_name: backend
    restart: always
    ports:
      - 3000:3000
  postgres:
    container_name: postgres
    image: postgres:16.1
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: test12345
      POSTGRES_DB: posts
    volumes:
      - ./volume/postgres/data:/var/lib/postgresql/data
    ports: 
      - 5555:5432